### ISSUE TITLE
Preprocessing scripts missing?

### ISSUE THREAD

**Issue by nhooram** [LynetteXing1991/HRAN#1]
Hi, I am really excited to try out your algorithm. I cloned the repo and tried to train on the data you provided. The first issue I encountered was that there is no module named `attention_with_posTagging`. I just kind of bypassed this by using the `SequenceContentAttention` in place of `SequenceContentAttention_withExInput`. After that, it gave me an error that the vocab files were missing (and presumably other files pointed by `src_data`, `trg_data`, etc. in the configurations file). I am guessing these file are results of the preprocessing pipeline you discussed in section 5.1 of the paper. I looked through the code to find a script that performs this preprocessing to no avail. Maybe you forgot to commit them? Thanks a bunch!

**Comment by LynetteXing1991** [comment]
I'm really sorry for the late reply~ I've attended AAAI-17 a few days before~
Thank you very much for your notice~

Yes, a preprocessing file and the py file with attention_with_posTagging is missing. I'll commit them immediately.
